2019-11-28 14:32:24,943 ERROR: Exception on /auth/reset_password_request [POST] [in /home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/blog/app/auth/routes.py", line 57, in reset_password_request
    send_password_reset_email(user)
  File "/home/ubuntu/blog/app/auth/email.py", line 14, in send_password_reset_email
    user=user, token=token))
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/blog/app/templates/email/reset_password.html", line 9, in top-level template code
    <p>{{ url_for('reset_password', token=token, _external=True) }}</p>
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/ubuntu/.local/lib/python3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2019-11-28 14:35:50,807 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 14:37:10,291 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 14:46:56,385 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-28 14:49:49,476 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-29 16:00:49,520 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-29 16:02:35,879 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-29 16:04:22,599 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-29 16:06:27,906 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-29 16:08:17,067 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-29 16:08:26,534 ERROR: Exception on /auth/reset_password_request [GET] [in /home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/blog/app/auth/routes.py", line 61, in reset_password_request
    title='Reset Password', form=form)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/blog/app/templates/auth/reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/ubuntu/blog/app/templates/auth/reset_password_request.html", line 14, in root
    </div>
  File "/home/ubuntu/blog/app/templates/base.html", line 14, in root
    {% block styles %}
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block_doc
    {% block body -%}
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 39, in block_html
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 92, in block_body
  File "/home/ubuntu/blog/app/templates/auth/reset_password_request.html", line 25, in block_content
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
2019-11-29 16:08:46,593 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-29 17:38:05,173 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-29 17:40:45,695 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-29 17:47:56,377 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-29 17:49:13,674 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-29 17:59:35,676 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-29 18:06:10,697 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-11-29 18:07:18,474 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
2019-12-01 11:47:58,976 INFO: 1st Woodhall Blog Startup [in /home/ubuntu/blog/app/__init__.py:66]
